### ISSUE TITLE
'Line does not support Text Values' errors in examples.

### ISSUE THREAD

**Issue by gwk** [wireservice/leather#81]
```
...
examples/mixed_shapes.py
Traceback (most recent call last):
  File "examples/mixed_shapes.py", line 26, in <module>
    chart.add_line(line_data)
  File "/Users/gwk/external/leather/leather/chart.py", line 175, in add_line
    Line(stroke_color, width)
  File "/Users/gwk/external/leather/leather/chart.py", line 130, in add_series
    shape.validate_series(series)
  File "/Users/gwk/external/leather/leather/shapes/line.py", line 36, in validate_series
    raise ValueError('Line does not support Text values.')
...
examples/theme.py
Traceback (most recent call last):
  File "examples/theme.py", line 31, in <module>
    chart.add_line(line_data)
  File "/Users/gwk/external/leather/leather/chart.py", line 175, in add_line
    Line(stroke_color, width)
  File "/Users/gwk/external/leather/leather/chart.py", line 130, in add_series
    shape.validate_series(series)
  File "/Users/gwk/external/leather/leather/shapes/line.py", line 36, in validate_series
    raise ValueError('Line does not support Text values.')
```

**Comment by onyxfish** [comment]
Thanks for catching this! This was a silent error in earlier versions (sort of worked but wasn't really supported). I made it a hard error before release but forgot to fix these examples. All better now!
